
title: Janyne Gomes
author: Janyne Gomes
email: janynnegomes@gmail.com
description: "Ajudo as empresas na construção de soluções digitais"
headline: "Software Engineer | Angular | Web & Mobile Development"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://devnetgomez.github.io" 
twitter_username: devnetgomez
github_username:  devnetgomez
mini_bio: Engenheira de Software com mais de 11 anos de experiência em desenvolvimento. Experiência internacional em BootCamp de robótica na NASA GSFC nos EUA. Sólidos conhecimentos em UML, OOP, Java, PHP, Javascript, Angular, NodeJS, MySQL, Ionic, WordPress, Jasmine, PHPUnit e Scrum. Forte relacionamento interpessoal com facilidade de comunicação em inglês e português. 

contact: disqus
disqus_shortname: devnetgomez-github-io


# Build settings
markdown: kramdown
theme: minima

collections:
  portfolios:
     output: true

defaults:
  - scope:
      path: ""
      type: "portfolios"
    values:
      layout: "portfolio"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
     
